/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    'from-sky-50',
    'from-sky-100',
    'from-sky-200',
    'from-sky-300',
    'from-sky-400',
    'from-sky-500',
    'from-sky-600',
    'to-sky-400',
    'to-sky-500',
    'to-sky-600',
    'from-cyan-50',
    'from-cyan-100',
    'from-cyan-200',
    'from-cyan-300',
    'from-cyan-400',
    'from-cyan-500',
    'from-cyan-600',
    'to-cyan-400',
    'to-cyan-500',
    'to-cyan-600',
    'from-teal-50',
    'from-teal-100',
    'from-teal-200',
    'from-teal-300',
    'from-teal-400',
    'from-teal-500',
    'from-teal-600',
    'to-teal-400',
    'to-teal-500',
    'to-teal-600',
    'from-emerald-50',
    'from-emerald-100',
    'from-emerald-200',
    'from-emerald-300',
    'from-emerald-400',
    'from-emerald-500',
    'from-emerald-600',
    'to-emerald-400',
    'to-emerald-500',
    'to-emerald-600',
    'shadow-sky-200',
    'shadow-cyan-200',
    'shadow-teal-200',
    'shadow-emerald-200',
    'via-sky-300',
    'via-cyan-300',
    'via-teal-300',
    'via-emerald-300',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "pulse-slow": {
          '0%, 100%': { opacity: 0.3 },
          '50%': { opacity: 0.5 },
        },
        "float": {
          '0%': { transform: 'translateY(0px) rotate(-12deg)' },
          '50%': { transform: 'translateY(-20px) rotate(-8deg)' },
          '100%': { transform: 'translateY(0px) rotate(-12deg)' },
        },
        "shimmer": {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-slow": "pulse-slow 8s ease-in-out infinite",
        "float": "float 12s ease-in-out infinite",
        "shimmer": "shimmer 2s infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

